name: Push to DOKS and update Kustomize

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and push to DOCR

    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build container image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t registry.digitalocean.com/nginx-container/clojure:$IMAGE_TAG .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        env:
          DOCR_REGISTRY: ${{ secrets.DOCR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
        run: docker push registry.digitalocean.com/$DOCR_REGISTRY/clojure:$IMAGE_TAG

  deploy-dev:
    name:
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
      - name: Checkout Kustomize repo
        uses: actions/checkout@v3
        with:
          repository: Lisa-Stats/do-clj-kustomize
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Set new image in config repo
        env:
          DOCR_REPOSITORY: clojure
          IMAGE_TAG: ${{ github.sha }}
        run: kustomize edit set image IMAGE:TAG=registry.digitalocean.com/nginx-container/$DOCR_REPOSITORY:$IMAGE_TAG
        working-directory: overlays/dev

      - name: Commit new image tag to repo
        run: |
          git config user.email "lisa.stathopulos@gmail.com"
          git config user.name "Lisa-Stats"
          git commit -am "Update dev image tag"
          git pull --rebase
          git push
